##########################################################################
# Title:         Sandbox: Pelican | Default Variables                     #
# Author(s):     kungfoome                                                   #
# URL:           https://github.com/saltyorg/Sandbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

pelican_name: pelican

################################
# Paths
################################

pelican_paths_folder: "{{ pelican_name }}"
pelican_paths_location: "{{ server_appdata_path }}/{{ pelican_paths_folder }}"
pelican_paths_folders_list:
  - "{{ pelican_paths_location }}"
  - "{{ pelican_paths_location }}/logs"
  - "{{ pelican_paths_location }}/data"

################################
# Web
################################

pelican_web_subdomain: "{{ pelican_name }}"
pelican_web_domain: "{{ user.domain }}"
pelican_web_port: "80"
pelican_web_url: "{{ 'https://' + (pelican_web_subdomain + '.' + pelican_web_domain
                if (pelican_web_subdomain | length > 0)
                else pelican_web_domain) }}"

################################
# DNS
################################

pelican_dns_record: "{{ pelican_web_subdomain }}"
pelican_dns_zone: "{{ pelican_web_domain }}"
pelican_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

pelican_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
pelican_traefik_middleware_default: "{{ traefik_default_middleware }}"
pelican_traefik_middleware_custom: ""
pelican_traefik_certresolver: "{{ traefik_default_certresolver }}"
pelican_traefik_enabled: true

################################
# Docker
################################

# Container
pelican_docker_container: "{{ pelican_name }}"

# Image
pelican_docker_image_pull: true
pelican_docker_image_tag: "latest"
pelican_docker_image: "ghcr.io/pelican-dev/panel:{{ pelican_docker_image_tag }}"

# Ports
pelican_docker_ports_defaults: []
pelican_docker_ports_custom: []
pelican_docker_ports: "{{ pelican_docker_ports_defaults
                         + pelican_docker_ports_custom }}"

# Envs
pelican_docker_envs_default:
  APP_URL: "{{ pelican_web_url }}"
  ADMIN_EMAIL: "{{ user.email }}"
  APP_DEBUG: "false"
  APP_ENV: "production"
  MAIL_DRIVER: "log"
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  XDG_DATA_HOME: "/pelican-data"

pelican_docker_envs_custom: {}
pelican_docker_envs: "{{ pelican_docker_envs_default
                        | combine(pelican_docker_envs_custom) }}"

# Commands
pelican_docker_commands_default: []
pelican_docker_commands_custom: []
pelican_docker_commands: "{{ pelican_docker_commands_default
                           + pelican_docker_commands_custom }}"

# Volumes
pelican_docker_volumes_default:
  - "{{ pelican_paths_location }}/logs:/var/www/html/storage/logs"
  - "{{ pelican_paths_location }}/data:/pelican-data"

pelican_docker_volumes_custom: []
pelican_docker_volumes: "{{ pelican_docker_volumes_default
                           + pelican_docker_volumes_custom }}"

# Devices
pelican_docker_devices_default: []
pelican_docker_devices_custom: []
pelican_docker_devices: "{{ pelican_docker_devices_default
                           + pelican_docker_devices_custom }}"

# Hosts
pelican_docker_hosts_default: {}
pelican_docker_hosts_custom: {}
pelican_docker_hosts: "{{ docker_hosts_common
                         | combine(pelican_docker_hosts_default)
                         | combine(pelican_docker_hosts_custom) }}"

# Labels
pelican_docker_labels_default: {}
pelican_docker_labels_custom: {}
pelican_docker_labels: "{{ docker_labels_common
                          | combine(pelican_docker_labels_default)
                          | combine(pelican_docker_labels_custom) }}"

# Hostname
pelican_docker_hostname: "{{ pelican_name }}"

# Networks
pelican_docker_networks_alias: "{{ pelican_name }}"
pelican_docker_networks_default: []
pelican_docker_networks_custom: []
pelican_docker_networks: "{{ docker_networks_common
                            + pelican_docker_networks_default
                            + pelican_docker_networks_custom }}"

# Capabilities
pelican_docker_capabilities_default: []
pelican_docker_capabilities_custom: []
pelican_docker_capabilities: "{{ pelican_docker_capabilities_default
                               + pelican_docker_capabilities_custom }}"

# Security Opts
pelican_docker_security_opts_default: []
pelican_docker_security_opts_custom: []
pelican_docker_security_opts: "{{ pelican_docker_security_opts_default
                                + pelican_docker_security_opts_custom }}"

# Restart Policy
pelican_docker_restart_policy: unless-stopped

# State
pelican_docker_state: started 